project:
  type: website

website:
  title: "Course template"
  page-navigation: true
  page-footer:
    right: "This website is built and maintained with ☕ and [Quarto](https://quarto.org/)."
  sidebar:
    tools:
      - icon: github
        menu:
          - text: Source code
            url:  https://github.com/UtrechtUniversity/rdm-quarto-workshop-template
          - text: Report an issue
            url:  https://github.com/UtrechtUniversity/rdm-quarto-workshop-template/issues
    search: true
    pinned: true
    alignment: center
    style: docked
    collapse-level: 2
    logo: img/uu-logo-en-geenwitruimte.png
    logo-alt: "Logo of Utrecht University"
    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
          - href: modules/setup.qmd
      - section: "Contents"
        contents:
          - href: modules/module1.qmd
            text: Introduction
          - href: modules/module2.qmd
            text: Files and directories
          - href: modules/module3.qmd
            text: Creating and editing files
          - href: modules/module4.qmd
            text: Pipes and filters
          - href: modules/module5.qmd
            text: Scripts, variables and parallelization
          - href: modules/module6.qmd
            text: SSH and SCP
          - href: modules/contact.qmd
            text: Contact

format:
  html:
    theme: 
      light: [cosmo, styles/theme-light.scss]
      dark: [cosmo, styles/theme-dark.scss]

